spring:
  application:
    name: onepiece_graphql_api
  graphql:
    graphiql:
      enabled: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database
#    username: your_username
#    password: your_password
#    driver-class-name: org.postgresql.Driver