spring:
  application:
    name: onepiece_graphql_api
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/peak_fiction_db
    username: oda
    password: god_tier
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    user: oda
    password: god_tier


#logging:
#  level:
#    root: debug