spring:
  application:
    name: onepiece_graphql_api
  config:
    import: optional:file:.env[.properties]
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true