spring:
  application:
    name: onepiece_characters
  config:
    import: optional:file:.env[.properties]
  graphql:
    graphiql:
      enabled: true
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    enabled: true
